name = recipe_maker
title = Craft Recipe Maker
description = Graphical recipe code generator for Luanti modding.
author = localuser
optional_depends = default, mcl_core, mcl_mangrove, mcl_cherry_blossom, mcl_bamboo, mcl_crimson, mcl_lanterns, mcl_mesh_items
